endpoint_weighting: true
jaeger_base_url: http://localhost:16686
limit_traces: 20
lookback_minutes: 10
output_dir: data/raw/traces
scom_threshold: 0.5
service_name: scenario1
threshold_method: percentile
threshold_percentile: 25.0
threshold_zscore: -1.5
